declare module 'vue' {
  export type {
    App,
    Component,
    ComponentCustomProperties,
    ComponentOptionsMixin,
    ComponentPublicInstance,
    ComputedRef,
    DefineComponent,
    SetupContext,
    InjectionKey,
    PropType,
    Ref,
    Slots,
    SlotsType,
    VNode,
    VNodeRef,
    WritableComputedRef,
  } from 'vue'

  export {
    Transition,
    TransitionGroup,
    TransitionProps,
    computed,
    createApp,
    defineComponent,
    getCurrentInstance,
    h,
    inject,
    nextTick,
    onActivated,
    onBeforeMount,
    onBeforeUnmount,
    onBeforeUpdate,
    onDeactivated,
    onErrorCaptured,
    onMounted,
    onServerPrefetch,
    onUnmounted,
    onUpdated,
    provide,
    reactive,
    ref,
    toRefs,
    watch,
    watchEffect,
    watchPostEffect,
    watchSyncEffect,
  } from 'vue'

}
